# Generated by Django 3.2.8 on 2021-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=191)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FileField(upload_to='files')),
                ('executed', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(null=True)),
                ('sku', models.CharField(blank=True, max_length=191, null=True)),
                ('msrp', models.CharField(blank=True, max_length=191, null=True)),
                ('map', models.CharField(blank=True, max_length=191, null=True)),
                ('our_price', models.CharField(blank=True, max_length=191, null=True)),
                ('brand', models.CharField(blank=True, max_length=191, null=True)),
                ('field_not_empty', models.CharField(blank=True, max_length=191, null=True)),
                ('rules', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(null=True)),
                ('what', models.CharField(blank=True, max_length=191, null=True)),
                ('for_what', models.CharField(blank=True, max_length=191, null=True)),
                ('field', models.CharField(blank=True, max_length=191, null=True)),
                ('ignore_sku', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField(null=True)),
                ('loader_id', models.IntegerField(null=True)),
                ('type', models.CharField(blank=True, max_length=191, null=True)),
                ('sheet_id', models.IntegerField(null=True)),
                ('sheets', models.CharField(blank=True, max_length=191, null=True)),
                ('start_from', models.CharField(blank=True, max_length=191, null=True)),
                ('remove_charter_all', models.CharField(blank=True, max_length=191, null=True)),
                ('remove_charter', models.CharField(blank=True, max_length=191, null=True)),
                ('remove_charter_sku', models.CharField(blank=True, max_length=191, null=True)),
                ('r_what', models.TextField(blank=True)),
                ('r_forwhat', models.TextField(blank=True)),
                ('r_from_sku', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=191, null=True)),
                ('msrp', models.CharField(blank=True, max_length=191, null=True)),
                ('map', models.CharField(blank=True, max_length=191, null=True)),
                ('our_price', models.CharField(blank=True, max_length=191, null=True)),
                ('field_not_empty', models.CharField(blank=True, max_length=191, null=True)),
                ('rules', models.TextField(blank=True)),
                ('ignore_skus', models.TextField(blank=True)),
                ('checkbox', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
