# Generated by Django 3.2.8 on 2022-01-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_rule_start_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(blank=True, max_length=191, null=True)),
                ('forwhat', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
    ]
