# Generated by Django 3.2.8 on 2022-01-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_replace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rcharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(null=True)),
                ('what', models.CharField(blank=True, max_length=191, null=True)),
                ('forwhat', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rsku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField(null=True)),
                ('what', models.CharField(blank=True, max_length=191, null=True)),
                ('forwhat', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
    ]
