# Generated by Django 3.2.8 on 2021-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('sku', models.CharField(blank=True, default=None, max_length=191, null=True)),
                ('msrp', models.CharField(blank=True, default=None, max_length=191, null=True)),
                ('map', models.CharField(blank=True, default=None, max_length=191, null=True)),
                ('our_price', models.CharField(blank=True, default=None, max_length=191, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=191, null=True)),
                ('key', models.CharField(blank=True, default=None, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
